name: tWS Testing

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      rs-src: ${{ steps.filter.outputs.rs-src }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4
        id: filter
        with:
          filters: |
            rs-src:
              - 'tws/**'
              - 'integration-tests/**'
              - 'storage/**'
              - 'openapi.yaml'
              - '.github/workflows/tws-testing.yml'

  rust-integration-test:
    name: rust-integration-test (${{ matrix.profile }})
    needs: changes
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - profile: onprem
            docker-init-services: mariadb-init
          - profile: aws
            docker-init-services: postgres-init
    defaults:
      run:
        working-directory: integration-tests
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: 3.14

      - uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: Install Python dependencies
        run: uv sync

      - name: Check formatting
        run: make check

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - uses: mozilla-actions/sccache-action@9e7fa8a12102821edf02ca5dbea1acd0f89a2696 # v0.0.10

      - name: Set Rust caching env vars
        run: |
          echo "SCCACHE_GHA_ENABLED=true" >> $GITHUB_ENV
          echo "RUSTC_WRAPPER=sccache" >> $GITHUB_ENV

      - name: Check Rust formatting
        if: needs.changes.outputs.rs-src == 'true'
        working-directory: tws
        run: cargo fmt --all -- --check

      - name: Build binaries
        if: needs.changes.outputs.rs-src == 'true'
        working-directory: tws
        run: cargo build

      - name: Start containers
        if: needs.changes.outputs.rs-src == 'true'
        run: docker compose up -d

      - name: Wait for init services
        if: needs.changes.outputs.rs-src == 'true'
        run: docker compose wait ${{ matrix.docker-init-services }}

      - name: Run integration tests
        if: needs.changes.outputs.rs-src == 'true'
        timeout-minutes: 5
        run: uv run pytest --durations=50
        env:
          TWS_TEST_PROFILE: ${{ matrix.profile }}

      - name: Shutdown containers
        if: needs.changes.outputs.rs-src == 'true'
        run: docker compose down --remove-orphans -v --timeout 5 || true
